//! Lucide icon geometry.
//!
//! Rio's `sugarloaf` exposes filled primitives only (`rect`, `line`,
//! `arc`, `polygon`) — there is no SVG renderer (its `components::svg`
//! module is commented out). So the icons are kept here as the exact
//! stroke geometry of the real [Lucide](https://lucide.dev) sources,
//! pre-decomposed: each icon's `d`/`rect`/`line` markup was converted
//! offline into the 2px-wide line segments and circular arcs its stroke
//! covers, on Lucide's 24x24 grid. No path is hand-drawn and no icon is
//! faked with a Unicode glyph.
//!
//! `Seg::*` coordinates are on that 24x24 grid; [`IconPlacement`] maps
//! them onto the window and scales the 2px stroke along with them.

/// One stroke of an icon, on Lucide's 24x24 grid.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Seg {
    Line {
        x1: f32,
        y1: f32,
        x2: f32,
        y2: f32,
    },
    /// A stroked circular arc: the stroke follows the circle of radius
    /// `r` around `(cx, cy)` from `start_deg` to `end_deg`.
    ///
    /// Angles are screen-space: 0 is +x (right) and 90 is +y (down),
    /// matching `sugarloaf`'s `arc`. A stroke is direction-agnostic, so
    /// `start_deg` is always the smaller angle and `end_deg` may exceed
    /// 360.
    Arc {
        cx: f32,
        cy: f32,
        r: f32,
        start_deg: f32,
        end_deg: f32,
    },
}

/// Lucide draws every icon in this box.
pub const LUCIDE_GRID: f32 = 24.0;
/// Lucide's default stroke width, in grid units.
pub const LUCIDE_STROKE: f32 = 2.0;

/// The icons the chrome paints.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Icon {
    /// `server` — the Hosts section.
    Server,
    /// `arrow-right-left` — the Port forwards section.
    ArrowRightLeft,
    /// `folder` — the SFTP section.
    Folder,
    /// `sliders-horizontal` — the Settings section.
    SlidersHorizontal,
    /// `plus` — the add-host affordance.
    Plus,
}

impl Icon {
    /// The stroke segments, verbatim from the Lucide source of that name.
    pub fn segments(self) -> &'static [Seg] {
        match self {
            Icon::Server => SERVER,
            Icon::ArrowRightLeft => ARROW_RIGHT_LEFT,
            Icon::Folder => FOLDER,
            Icon::SlidersHorizontal => SLIDERS_HORIZONTAL,
            Icon::Plus => PLUS,
        }
    }
}

/// Where an icon is being drawn, and at what size.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct IconPlacement {
    /// Top-left corner of the icon box, in logical pixels.
    pub x: f32,
    pub y: f32,
    /// Side of the (square) icon box, in logical pixels.
    pub size: f32,
}

impl IconPlacement {
    pub const fn new(x: f32, y: f32, size: f32) -> Self {
        Self { x, y, size }
    }

    /// Grid units -> logical pixels.
    pub fn scale(&self) -> f32 {
        self.size / LUCIDE_GRID
    }

    /// Stroke width in logical pixels.
    pub fn stroke(&self) -> f32 {
        LUCIDE_STROKE * self.scale()
    }

    /// Map a grid point onto the window.
    pub fn map(&self, gx: f32, gy: f32) -> (f32, f32) {
        let s = self.scale();
        (self.x + gx * s, self.y + gy * s)
    }
}

// ---- generated: do not edit ----
// Regenerated by `scripts/gen-lucide-icons.py --write` from the Lucide
// sources; run `cargo fmt -p terminus-ui` afterwards.

/// `server`
const SERVER: &[Seg] = &[
    Seg::Line {
        x1: 6.0,
        y1: 6.0,
        x2: 6.01,
        y2: 6.0,
    },
    Seg::Line {
        x1: 6.0,
        y1: 18.0,
        x2: 6.01,
        y2: 18.0,
    },
    Seg::Line {
        x1: 4.0,
        y1: 2.0,
        x2: 20.0,
        y2: 2.0,
    },
    Seg::Arc {
        cx: 20.0,
        cy: 4.0,
        r: 2.0,
        start_deg: 270.00,
        end_deg: 360.00,
    },
    Seg::Line {
        x1: 22.0,
        y1: 4.0,
        x2: 22.0,
        y2: 8.0,
    },
    Seg::Arc {
        cx: 20.0,
        cy: 8.0,
        r: 2.0,
        start_deg: 0.00,
        end_deg: 90.00,
    },
    Seg::Line {
        x1: 20.0,
        y1: 10.0,
        x2: 4.0,
        y2: 10.0,
    },
    Seg::Arc {
        cx: 4.0,
        cy: 8.0,
        r: 2.0,
        start_deg: 90.00,
        end_deg: 180.00,
    },
    Seg::Line {
        x1: 2.0,
        y1: 8.0,
        x2: 2.0,
        y2: 4.0,
    },
    Seg::Arc {
        cx: 4.0,
        cy: 4.0,
        r: 2.0,
        start_deg: 180.00,
        end_deg: 270.00,
    },
    Seg::Line {
        x1: 4.0,
        y1: 14.0,
        x2: 20.0,
        y2: 14.0,
    },
    Seg::Arc {
        cx: 20.0,
        cy: 16.0,
        r: 2.0,
        start_deg: 270.00,
        end_deg: 360.00,
    },
    Seg::Line {
        x1: 22.0,
        y1: 16.0,
        x2: 22.0,
        y2: 20.0,
    },
    Seg::Arc {
        cx: 20.0,
        cy: 20.0,
        r: 2.0,
        start_deg: 0.00,
        end_deg: 90.00,
    },
    Seg::Line {
        x1: 20.0,
        y1: 22.0,
        x2: 4.0,
        y2: 22.0,
    },
    Seg::Arc {
        cx: 4.0,
        cy: 20.0,
        r: 2.0,
        start_deg: 90.00,
        end_deg: 180.00,
    },
    Seg::Line {
        x1: 2.0,
        y1: 20.0,
        x2: 2.0,
        y2: 16.0,
    },
    Seg::Arc {
        cx: 4.0,
        cy: 16.0,
        r: 2.0,
        start_deg: 180.00,
        end_deg: 270.00,
    },
];

/// `arrow-right-left`
const ARROW_RIGHT_LEFT: &[Seg] = &[
    Seg::Line {
        x1: 16.0,
        y1: 3.0,
        x2: 20.0,
        y2: 7.0,
    },
    Seg::Line {
        x1: 20.0,
        y1: 7.0,
        x2: 16.0,
        y2: 11.0,
    },
    Seg::Line {
        x1: 20.0,
        y1: 7.0,
        x2: 4.0,
        y2: 7.0,
    },
    Seg::Line {
        x1: 8.0,
        y1: 21.0,
        x2: 4.0,
        y2: 17.0,
    },
    Seg::Line {
        x1: 4.0,
        y1: 17.0,
        x2: 8.0,
        y2: 13.0,
    },
    Seg::Line {
        x1: 4.0,
        y1: 17.0,
        x2: 20.0,
        y2: 17.0,
    },
];

/// `folder`
const FOLDER: &[Seg] = &[
    Seg::Arc {
        cx: 20.0,
        cy: 18.0,
        r: 2.0,
        start_deg: 90.00,
        end_deg: 180.00,
    },
    Seg::Line {
        x1: 22.0,
        y1: 18.0,
        x2: 22.0,
        y2: 8.0,
    },
    Seg::Arc {
        cx: 20.0,
        cy: 8.0,
        r: 2.0,
        start_deg: 0.00,
        end_deg: 90.00,
    },
    Seg::Line {
        x1: 20.0,
        y1: 6.0,
        x2: 12.1,
        y2: 6.0,
    },
    Seg::Arc {
        cx: 12.0804,
        cy: 4.0001,
        r: 2.0,
        start_deg: 89.44,
        end_deg: 146.64,
    },
    Seg::Line {
        x1: 10.41,
        y1: 5.1,
        x2: 9.6,
        y2: 3.9,
    },
    Seg::Arc {
        cx: 7.92967,
        cy: 5.0,
        r: 2.0,
        start_deg: 326.63,
        end_deg: 383.26,
    },
    Seg::Line {
        x1: 7.93,
        y1: 3.0,
        x2: 4.0,
        y2: 3.0,
    },
    Seg::Arc {
        cx: 4.0,
        cy: 5.0,
        r: 2.0,
        start_deg: 270.00,
        end_deg: 360.00,
    },
    Seg::Line {
        x1: 2.0,
        y1: 5.0,
        x2: 2.0,
        y2: 18.0,
    },
    Seg::Arc {
        cx: 4.0,
        cy: 18.0,
        r: 2.0,
        start_deg: 180.00,
        end_deg: 270.00,
    },
    Seg::Line {
        x1: 4.0,
        y1: 20.0,
        x2: 20.0,
        y2: 20.0,
    },
];

/// `sliders-horizontal`
const SLIDERS_HORIZONTAL: &[Seg] = &[
    Seg::Line {
        x1: 10.0,
        y1: 5.0,
        x2: 3.0,
        y2: 5.0,
    },
    Seg::Line {
        x1: 12.0,
        y1: 19.0,
        x2: 3.0,
        y2: 19.0,
    },
    Seg::Line {
        x1: 14.0,
        y1: 3.0,
        x2: 14.0,
        y2: 7.0,
    },
    Seg::Line {
        x1: 16.0,
        y1: 17.0,
        x2: 16.0,
        y2: 21.0,
    },
    Seg::Line {
        x1: 21.0,
        y1: 12.0,
        x2: 12.0,
        y2: 12.0,
    },
    Seg::Line {
        x1: 21.0,
        y1: 19.0,
        x2: 16.0,
        y2: 19.0,
    },
    Seg::Line {
        x1: 21.0,
        y1: 5.0,
        x2: 14.0,
        y2: 5.0,
    },
    Seg::Line {
        x1: 8.0,
        y1: 10.0,
        x2: 8.0,
        y2: 14.0,
    },
    Seg::Line {
        x1: 8.0,
        y1: 12.0,
        x2: 3.0,
        y2: 12.0,
    },
];

/// `plus`
const PLUS: &[Seg] = &[
    Seg::Line {
        x1: 5.0,
        y1: 12.0,
        x2: 19.0,
        y2: 12.0,
    },
    Seg::Line {
        x1: 12.0,
        y1: 5.0,
        x2: 12.0,
        y2: 19.0,
    },
];

// ---- end generated ----

/// Largest angle one flattened arc segment may cover, in degrees.
///
/// `sugarloaf`'s `arc()` primitive ignores the caller's draw order (it
/// always lands in the order-0 batch, i.e. *under* the terminal grid),
/// so icons are emitted as `line` strips instead. At icon sizes this
/// step is well below a pixel of visible faceting.
pub const ARC_STEP_DEG: f32 = 12.0;

/// Flatten an icon into line segments on the 24x24 grid.
///
/// One `(from, to)` pair per `sugarloaf` `line()` call. Pure geometry:
/// the painter only maps the points and picks the stroke width.
pub fn flatten(icon: Icon) -> Vec<((f32, f32), (f32, f32))> {
    let mut lines = Vec::new();
    for segment in icon.segments() {
        match *segment {
            Seg::Line { x1, y1, x2, y2 } => lines.push(((x1, y1), (x2, y2))),
            Seg::Arc {
                cx,
                cy,
                r,
                start_deg,
                end_deg,
            } => {
                let sweep = end_deg - start_deg;
                let steps = (sweep / ARC_STEP_DEG).ceil().max(1.0) as usize;
                let mut previous = point_on(cx, cy, r, start_deg);
                for step in 1..=steps {
                    let angle = start_deg + sweep * (step as f32 / steps as f32);
                    let next = point_on(cx, cy, r, angle);
                    lines.push((previous, next));
                    previous = next;
                }
            }
        }
    }
    lines
}

/// A point on a circle, in screen angles (0 = +x, 90 = +y i.e. down).
pub fn point_on(cx: f32, cy: f32, r: f32, deg: f32) -> (f32, f32) {
    let radians = deg.to_radians();
    (cx + r * radians.cos(), cy + r * radians.sin())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every segment has to sit inside Lucide's 24x24 grid, or the
    /// placement mapping would put ink outside the icon box.
    #[test]
    fn every_icon_fits_the_lucide_grid() {
        for icon in [
            Icon::Server,
            Icon::ArrowRightLeft,
            Icon::Folder,
            Icon::SlidersHorizontal,
            Icon::Plus,
        ] {
            let segs = icon.segments();
            assert!(!segs.is_empty(), "{icon:?} has no strokes");
            for seg in segs {
                let points: Vec<(f32, f32)> = match *seg {
                    Seg::Line { x1, y1, x2, y2 } => vec![(x1, y1), (x2, y2)],
                    Seg::Arc {
                        cx,
                        cy,
                        r,
                        start_deg,
                        end_deg,
                    } => {
                        assert!(start_deg < end_deg, "{icon:?} arc sweeps backwards");
                        assert!(
                            end_deg - start_deg <= 360.0,
                            "{icon:?} arc sweeps more than a full turn"
                        );
                        vec![(cx, cy), (cx - r, cy - r), (cx + r, cy + r)]
                    }
                };
                for (x, y) in points {
                    // The stroke is 2 units wide, i.e. 1 unit either
                    // side of the centerline.
                    assert!(
                        (-1.0..=LUCIDE_GRID + 1.0).contains(&x)
                            && (-1.0..=LUCIDE_GRID + 1.0).contains(&y),
                        "{icon:?} draws at ({x}, {y}) outside the grid"
                    );
                }
            }
        }
    }

    #[test]
    fn flattened_icons_keep_every_segment_inside_the_grid() {
        for icon in [
            Icon::Server,
            Icon::ArrowRightLeft,
            Icon::Folder,
            Icon::SlidersHorizontal,
            Icon::Plus,
        ] {
            for ((x1, y1), (x2, y2)) in flatten(icon) {
                for (x, y) in [(x1, y1), (x2, y2)] {
                    assert!(
                        (-1.0..=LUCIDE_GRID + 1.0).contains(&x)
                            && (-1.0..=LUCIDE_GRID + 1.0).contains(&y),
                        "{icon:?} draws at ({x}, {y}) outside the grid"
                    );
                }
            }
        }
    }

    #[test]
    fn arcs_flatten_to_short_segments_that_keep_their_endpoints() {
        let lines = flatten(Icon::Server);
        // 2 dots + 2 rounded rects (4 edges + 4 corners each).
        assert_eq!(Icon::Server.segments().len(), 18);
        assert!(
            lines.len() > Icon::Server.segments().len(),
            "arcs did not expand: {} strips for {} segments",
            lines.len(),
            Icon::Server.segments().len()
        );

        // The top-right corner of the first rect: radius 2 about
        // (20, 4), sweeping 270 -> 360 degrees. Both ends of each strip
        // are on that circle; the neighbouring straight edges are not.
        let on_arc = |(x, y): (f32, f32)| {
            let r = ((x - 20.0).powi(2) + (y - 4.0).powi(2)).sqrt();
            (r - 2.0).abs() < 1e-3
        };
        let corner: Vec<_> = lines
            .iter()
            .filter(|(from, to)| on_arc(*from) && on_arc(*to))
            .collect();
        assert!(
            corner.len() >= 8,
            "corner flattened to only {} strips",
            corner.len()
        );

        for (from, to) in corner {
            let chord = ((to.0 - from.0).powi(2) + (to.1 - from.1).powi(2)).sqrt();
            assert!(chord < 1.0, "strip of length {chord} is too coarse");
        }

        // The far end of the same arc is reached exactly (360 == 0 deg).
        let end = point_on(20.0, 4.0, 2.0, 360.0);
        assert!(lines
            .iter()
            .any(|(_, to)| (to.0 - end.0).abs() < 1e-4 && (to.1 - end.1).abs() < 1e-4));
    }

    #[test]
    fn point_on_follows_screen_angles() {
        let (x, y) = point_on(0.0, 0.0, 10.0, 0.0);
        assert!((x - 10.0).abs() < 1e-4 && y.abs() < 1e-4);
        // 90 degrees is *down* on screen, not up.
        let (x, y) = point_on(0.0, 0.0, 10.0, 90.0);
        assert!(x.abs() < 1e-4 && (y - 10.0).abs() < 1e-4);
    }

    #[test]
    fn placement_scales_the_stroke_with_the_icon() {
        let small = IconPlacement::new(0.0, 0.0, 12.0);
        let large = IconPlacement::new(0.0, 0.0, 24.0);
        assert_eq!(large.scale(), 1.0);
        assert_eq!(large.stroke(), LUCIDE_STROKE);
        assert_eq!(small.stroke(), LUCIDE_STROKE / 2.0);
    }

    #[test]
    fn placement_maps_the_grid_onto_the_box() {
        let p = IconPlacement::new(100.0, 50.0, 18.0);
        assert_eq!(p.map(0.0, 0.0), (100.0, 50.0));
        assert_eq!(p.map(24.0, 24.0), (118.0, 68.0));
        // Grid center lands on the box center.
        assert_eq!(p.map(12.0, 12.0), (109.0, 59.0));
    }
}
