//! Ensure / invoke the remote `terminus-walk` helper (jwalk) for SFTP diffs.

use std::path::{Path, PathBuf};

use terminus_core::ssh::SftpConnection;
use terminus_walk::{
    hash_paths, parse_digests, parse_meta, snapshot_meta, MetaMap, TOOL_NAME,
    TOOL_VERSION,
};

use super::{probe_remote_env, shell_quote, RemoteEnv, RemoteFamily};

fn normalize_arch(arch: &str) -> &str {
    match arch {
        "x86_64" | "amd64" => "x86_64",
        "aarch64" | "arm64" => "aarch64",
        other => other,
    }
}

fn local_arch_triple() -> &'static str {
    match std::env::consts::ARCH {
        "x86_64" => "x86_64-unknown-linux-musl",
        "aarch64" => "aarch64-unknown-linux-musl",
        _ => "x86_64-unknown-linux-musl",
    }
}

/// Bytes of the portable (musl) walker, baked in at compile time via build.rs.
fn embedded_walk_bytes() -> &'static [u8] {
    // Generated by crates/terminus-bridge/build.rs into OUT_DIR.
    include_bytes!(concat!(env!("OUT_DIR"), "/terminus-walk.embedded"))
}

/// Materialize the embedded walker to a stable cache path (chmod +x).
fn extract_embedded_walk_binary() -> Result<PathBuf, String> {
    let bytes = embedded_walk_bytes();
    if bytes.is_empty() {
        return Err(
            "terminus-walk was not embedded at build time; run: cargo build -p terminus-walk --release --target x86_64-unknown-linux-musl && cargo build -p terminus-bridge"
                .into(),
        );
    }
    let dir = std::env::temp_dir().join("terminus-walk-bin");
    std::fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
    let dest = dir.join(format!(
        "{TOOL_NAME}-v{TOOL_VERSION}-{}",
        std::env::consts::ARCH
    ));
    let need_write = match std::fs::metadata(&dest) {
        Ok(m) => m.len() != bytes.len() as u64,
        Err(_) => true,
    };
    if need_write {
        std::fs::write(&dest, bytes)
            .map_err(|e| format!("extract terminus-walk: {e}"))?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mut perms = std::fs::metadata(&dest)
                .map_err(|e| e.to_string())?
                .permissions();
            perms.set_mode(0o755);
            std::fs::set_permissions(&dest, perms).map_err(|e| e.to_string())?;
        }
    }
    Ok(dest)
}

/// Locate a **portable** walker: search disk first, else extract the embedded musl binary.
pub(super) fn find_local_walk_binary() -> Result<PathBuf, String> {
    if let Ok(p) = std::env::var("TERMINUS_WALK_BIN") {
        let p = PathBuf::from(p);
        if p.is_file() {
            return Ok(p);
        }
        return Err(format!(
            "TERMINUS_WALK_BIN set but not a file: {}",
            p.display()
        ));
    }

    let triple = local_arch_triple();
    let mut candidates: Vec<PathBuf> = Vec::new();

    let push_target_dirs = |candidates: &mut Vec<PathBuf>, root: &Path| {
        candidates.push(root.join(format!("target/{triple}/release/{TOOL_NAME}")));
        candidates.push(root.join(format!("target/{triple}/debug/{TOOL_NAME}")));
        candidates.push(root.join(format!("target/release/{TOOL_NAME}")));
        candidates.push(root.join(format!("target/debug/{TOOL_NAME}")));
        candidates.push(root.join(format!("target/debug/{TOOL_NAME}-musl")));
    };

    let manifest = Path::new(env!("CARGO_MANIFEST_DIR"));
    if let Some(ws) = manifest.parent().and_then(|p| p.parent()) {
        push_target_dirs(&mut candidates, ws);
    }
    candidates.push(manifest.join(format!("../../target/{triple}/release/{TOOL_NAME}")));

    if let Ok(exe) = std::env::current_exe() {
        if let Some(dir) = exe.parent() {
            candidates.push(dir.join(TOOL_NAME));
            candidates.push(dir.join(format!("{TOOL_NAME}-musl")));
            let mut cur = dir.to_path_buf();
            for _ in 0..6 {
                push_target_dirs(&mut candidates, &cur);
                if !cur.pop() {
                    break;
                }
            }
        }
    }

    if let Ok(cwd) = std::env::current_dir() {
        let mut cur = cwd;
        for _ in 0..6 {
            push_target_dirs(&mut candidates, &cur);
            if !cur.pop() {
                break;
            }
        }
    }

    for candidate in &candidates {
        if candidate.is_file() {
            let resolved = candidate.canonicalize().map_err(|e| e.to_string())?;
            return Ok(resolved);
        }
    }

    // Disk miss → extract the musl binary that was embedded when terminus-bridge was built.
    extract_embedded_walk_binary()
}

/// Upload `terminus-walk` once per remote (versioned path under remote tmp).
pub(super) async fn ensure_remote_walk(
    conn: &SftpConnection,
) -> Result<(String, RemoteEnv), String> {
    let env = probe_remote_env(conn).await;
    if env.family != RemoteFamily::Unix {
        return Err("terminus-walk remote helper requires a Unix remote".into());
    }
    let local_arch = normalize_arch(std::env::consts::ARCH);
    let remote_arch = normalize_arch(&env.arch);
    if local_arch != remote_arch {
        return Err(format!(
            "CPU arch mismatch (local {local_arch}, remote {remote_arch}); build terminus-walk for the remote arch"
        ));
    }

    let remote_bin = format!(
        "{}/.{}-v{}-{}",
        env.tmp.trim_end_matches('/'),
        TOOL_NAME,
        TOOL_VERSION,
        remote_arch
    );

    let ver_cmd = format!("{} --version", shell_quote(&remote_bin));
    if let Ok((0, stdout, _)) = conn.exec(&ver_cmd).await {
        let out = String::from_utf8_lossy(&stdout);
        if out.contains(TOOL_NAME) && out.contains(TOOL_VERSION) {
            return Ok((remote_bin, env));
        }
    }

    let local_bin = find_local_walk_binary()?;
    let bytes = tokio::fs::read(&local_bin)
        .await
        .map_err(|e| format!("read {}: {e}", local_bin.display()))?;
    conn.write(&remote_bin, &bytes)
        .await
        .map_err(|e| format!("upload terminus-walk: {e}"))?;
    let chmod = format!("chmod +x -- {}", shell_quote(&remote_bin));
    let (code, _, stderr) = conn.exec(&chmod).await.map_err(|e| e.to_string())?;
    if code != 0 {
        return Err(format!(
            "chmod terminus-walk failed: {}",
            String::from_utf8_lossy(&stderr)
        ));
    }
    let (code, stdout, stderr) = conn.exec(&ver_cmd).await.map_err(|e| e.to_string())?;
    let out = String::from_utf8_lossy(&stdout);
    let err = String::from_utf8_lossy(&stderr);
    if code != 0 || !out.contains(TOOL_VERSION) {
        return Err(format!(
            "remote terminus-walk not runnable after upload (need static musl build). stdout={out} stderr={err}"
        ));
    }
    Ok((remote_bin, env))
}

pub(super) async fn remote_walk_meta(
    conn: &SftpConnection,
    walk_bin: &str,
    root: &str,
) -> Result<MetaMap, String> {
    let cmd = format!("{} meta {}", shell_quote(walk_bin), shell_quote(root));
    let (code, stdout, stderr) = conn.exec(&cmd).await.map_err(|e| e.to_string())?;
    if code != 0 {
        return Err(format!(
            "remote walk meta failed: {}",
            String::from_utf8_lossy(&stderr)
        ));
    }
    parse_meta(&String::from_utf8_lossy(&stdout))
}

pub(super) async fn remote_walk_hash(
    conn: &SftpConnection,
    walk_bin: &str,
    root: &str,
    rels: &[String],
    tmp: &str,
) -> Result<terminus_walk::DigestMap, String> {
    if rels.is_empty() {
        return Ok(terminus_walk::DigestMap::new());
    }
    let list_path = format!(
        "{}/.terminus-walk-hash-{}.list",
        tmp.trim_end_matches('/'),
        std::process::id()
    );
    let mut list = Vec::new();
    for rel in rels {
        list.extend_from_slice(rel.as_bytes());
        list.push(b'\n');
    }
    conn.write(&list_path, &list)
        .await
        .map_err(|e| format!("write hash list: {e}"))?;
    let cmd = format!(
        "{} hash {} --list {}",
        shell_quote(walk_bin),
        shell_quote(root),
        shell_quote(&list_path)
    );
    let (code, stdout, stderr) = conn.exec(&cmd).await.map_err(|e| e.to_string())?;
    let _ = conn
        .exec(&format!("rm -f -- {}", shell_quote(&list_path)))
        .await;
    if code != 0 {
        return Err(format!(
            "remote walk hash failed: {}",
            String::from_utf8_lossy(&stderr)
        ));
    }
    parse_digests(&String::from_utf8_lossy(&stdout))
}

pub(super) fn local_walk_meta(root: &Path) -> Result<MetaMap, String> {
    snapshot_meta(root)
}

pub(super) fn local_walk_hash(
    root: &Path,
    rels: &[String],
) -> Result<terminus_walk::DigestMap, String> {
    hash_paths(root, rels)
}

pub(super) fn content_suspects(remote: &MetaMap, local: &MetaMap) -> Vec<String> {
    let mut out = Vec::new();
    for (rel, r) in remote {
        let Some(l) = local.get(rel) else {
            continue;
        };
        if r.size != l.size {
            continue;
        }
        match (r.mtime_ns, l.mtime_ns) {
            (Some(a), Some(b)) if a == b => {}
            _ => out.push(rel.clone()),
        }
    }
    out
}
