#!/usr/bin/env python3
"""Regenerate Simple Icons brand marks in `crates/terminus-ui/src/os_icons.rs`.

Sources SVG path `d` + brand hex from the upstream Simple Icons repo
(https://github.com/simple-icons/simple-icons), same 24×24 filled marks the
product mock uses for OS badges.

    scripts/gen-simple-icons.py --write
    cargo test -p terminus-ui --lib os_icons::

Without `--write` the generated Rust block is printed to stdout.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "crates" / "terminus-ui" / "src" / "os_icons.rs"
BEGIN = "// ---- generated simple-icons: do not edit ----"
END = "// ---- end generated simple-icons ----"

# Slug → Rust enum variant. Keep Windows out: Simple Icons dropped it.
ICONS: dict[str, str] = {
    "nixos": "NixOs",
    "ubuntu": "Ubuntu",
    "debian": "Debian",
    "fedora": "Fedora",
    "archlinux": "ArchLinux",
    "apple": "Apple",
    "linux": "Linux",
    "postgresql": "Postgresql",
    "redhat": "RedHat",
    "alpinelinux": "AlpineLinux",
    "centos": "CentOs",
    "opensuse": "OpenSuse",
    "gentoo": "Gentoo",
    "voidlinux": "VoidLinux",
    "rockylinux": "RockyLinux",
    "kalilinux": "KaliLinux",
    "linuxmint": "LinuxMint",
}

RAW_SVG = "https://raw.githubusercontent.com/simple-icons/simple-icons/master/icons/{slug}.svg"
RAW_DATA = "https://raw.githubusercontent.com/simple-icons/simple-icons/master/data/simple-icons.json"
PATH_RE = re.compile(r'<path\s+d="([^"]+)"', re.IGNORECASE)
TITLE_RE = re.compile(r"<title>([^<]+)</title>", re.IGNORECASE)


def fetch(url: str) -> str:
    with urllib.request.urlopen(url, timeout=30) as resp:
        return resp.read().decode("utf-8")


def slugify_title(title: str) -> str:
    """Approximate Simple Icons slug rules for matching JSON entries."""
    s = title.lower()
    s = s.replace("+", "plus").replace(".", "dot").replace("&", "and")
    s = re.sub(r"[^a-z0-9]+", "", s)
    return s


def load_hex_by_slug() -> dict[str, str]:
    data = json.loads(fetch(RAW_DATA))
    out: dict[str, str] = {}
    for icon in data:
        title = icon.get("title") or ""
        hex_color = icon.get("hex") or "888888"
        slug = slugify_title(title)
        out[slug] = hex_color
        for aka in (icon.get("aliases") or {}).get("aka") or []:
            out[slugify_title(aka)] = hex_color
    return out


def extract_path(svg: str) -> str:
    match = PATH_RE.search(svg)
    if not match:
        raise SystemExit(f"no <path d=...> in SVG:\n{svg[:200]}")
    return match.group(1)


def rust_string(value: str) -> str:
    return json.dumps(value)  # proper escaping


def generate_block(hex_by_slug: dict[str, str]) -> str:
    variants = list(ICONS.values())
    enum_body = ",\n    ".join(variants)

    records = []
    for slug, variant in ICONS.items():
        svg = fetch(RAW_SVG.format(slug=slug))
        path = extract_path(svg)
        title_m = TITLE_RE.search(svg)
        title = title_m.group(1) if title_m else slug
        hex_color = hex_by_slug.get(slug) or hex_by_slug.get(slugify_title(title))
        if not hex_color:
            raise SystemExit(f"no hex for {slug} ({title})")
        if len(hex_color) != 6 or any(c not in "0123456789abcdefABCDEF" for c in hex_color):
            raise SystemExit(f"bad hex {hex_color!r} for {slug}")
        records.append((variant, slug, title, hex_color.upper(), path))

    match_slug = "\n".join(
        f'            Self::{v} => "{s}",' for v, s, *_ in records
    )
    match_hex = "\n".join(
        f"            Self::{v} => \"{h}\"," for v, _s, _t, h, _p in records
    )
    match_path = "\n".join(
        f"            Self::{v} => {rust_string(p)}," for v, _s, _t, _h, p in records
    )
    match_title = "\n".join(
        f"            Self::{v} => {rust_string(t)}," for v, _s, t, _h, _p in records
    )

    # Discriminant order must match the enum declaration.
    all_list = ",\n            ".join(f"Self::{v}" for v, *_ in records)

    return f"""{BEGIN}
/// Brand marks vendored from [Simple Icons](https://github.com/simple-icons/simple-icons).
///
/// Regenerated by `scripts/gen-simple-icons.py --write`. Paths are the
/// official 24×24 filled `d` attributes; colours are the brand hex.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SimpleBrand {{
    {enum_body},
}}

impl SimpleBrand {{
    pub const ALL: [Self; {len(records)}] = [
            {all_list},
    ];

    pub const fn slug(self) -> &'static str {{
        match self {{
{match_slug}
        }}
    }}

    pub const fn title(self) -> &'static str {{
        match self {{
{match_title}
        }}
    }}

    /// Brand hex without `#` (e.g. `5277C3`).
    pub const fn hex(self) -> &'static str {{
        match self {{
{match_hex}
        }}
    }}

    /// SVG path `d` on the Simple Icons 24×24 grid (filled).
    pub const fn path_d(self) -> &'static str {{
        match self {{
{match_path}
        }}
    }}
}}
{END}
"""


def replace_block(source: str, block: str) -> str:
    if BEGIN in source and END in source:
        before, _, rest = source.partition(BEGIN)
        _, _, after = rest.partition(END)
        # Drop trailing newline duplication.
        return before.rstrip() + "\n\n" + block + "\n" + after.lstrip("\n")
    # Insert before HostStatus if present, else append.
    marker = "/// Status dot colour"
    if marker in source:
        head, tail = source.split(marker, 1)
        return head.rstrip() + "\n\n" + block + "\n\n" + marker + tail
    return source.rstrip() + "\n\n" + block + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="write into os_icons.rs")
    args = parser.parse_args()

    print("fetching Simple Icons metadata…", file=sys.stderr)
    hex_by_slug = load_hex_by_slug()
    print(f"fetching {len(ICONS)} SVGs…", file=sys.stderr)
    block = generate_block(hex_by_slug)

    if not args.write:
        sys.stdout.write(block)
        return 0

    source = TARGET.read_text()
    TARGET.write_text(replace_block(source, block))
    print(f"wrote {TARGET.relative_to(ROOT)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
